import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Askeza</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col min-safe-h-screen overflow-auto justify-between">
        <div className='my-auto'>
          <Image className="mx-auto" src="/assets/img/logo_text-grad-black.svg" alt="Vercel Logo" width={260} height={52} />
          <h1 className='block text-gray-100 w-64 text-xl text-center mx-auto font-raleway mt-5 font-extralight tracking-wide'>Новый способ отказаться от вредных привычек</h1>
        </div>
        <div className='mb-20'>
          <Link href="/about">
            <button className='font-extralight block mx-auto text-xl text-gray-100 bg-violet-background rounded-xl px-20 py-4'>
            Подробнее
            </button>
          </Link>
          <button className='font-extralight block lowercase mx-auto text-xl text-blue py-5'>Войти</button>
        </div>
      </main>
    </div>
  )
}
